namespace Glyphotype.RegexGeneration.Presentation;

/// <summary>
/// Turns the raw, unfiltered brick sequence produced by walking a <see cref="RegexNode"/> graph into the
/// sequence that gets rendered as commented output. In order: enum member value bricks are dropped and
/// regenerated by <see cref="EnumSectionBuilder"/> as occurrence-ranked, synonym-grouped rows; group
/// names are simplified via <see cref="RegexGraph.SimpleUniqueNames"/>; every brick's display comment is
/// resolved via <see cref="BrickCommentResolver"/>; and blank-line bricks are inserted between logical
/// sections. This replaces what used to be a single large method (<c>SmartRegex.GetSpacedFilteredRegexBricks</c>).
/// </summary>
internal class RegexBrickFormattingPipeline
{
    readonly RegexGraph _regexGraph;
    readonly GlyphOccurrenceSummary _summary;
    readonly RegexDisplayMode _displayMode;
    readonly EnumSectionBuilder _enumSectionBuilder = new();
    readonly DynamicSectionBuilder _dynamicSectionBuilder = new();

    public RegexBrickFormattingPipeline(RegexGraph regexGraph, GlyphOccurrenceSummary summary, RegexDisplayMode displayMode = RegexDisplayMode.MatchedOnly)
    {
        _regexGraph = regexGraph;
        _summary = summary;
        _displayMode = displayMode;
    }

    /// <summary>Runs the full formatting pass over <paramref name="bricks"/> and returns the final, render-ready brick sequence.</summary>
    /// <param name="includeSupplementalLines">
    /// Whether to include the purely-decorative/summary lines: <see cref="RegexBrickBlank"/> separators
    /// between logical sections, and each enum group's trailing <see cref="RegexBrickOmittedCount"/> row.
    /// </param>
    public List<RegexBrick> Format(List<RegexBrick> bricks, bool includeSupplementalLines = true)
    {
        // Bricks are shared/cached per type and re-formatted on every render. A brick embedded elsewhere
        // by DynamicSectionBuilder leaves depth/identity overrides applied on these same shared objects,
        // so a plain, non-embedded pass must clear them back to baseline here — otherwise a type rendered
        // on its own page would inherit stale depth or a rebased data-path from the last time it was
        // embedded inside some other type's dynamic capture. This must run over every raw brick, not just
        // the ones that survive RemoveRawSynthesizedSectionBricks below: enum member (RegexBrickValue)
        // bricks are filtered out of that sequence but re-fetched from this same unfiltered list by
        // EnumSectionBuilder, so they'd otherwise never get reset at all.
        foreach (var brick in bricks)
        {
            brick.ResetEmbeddingOverrides();

            // Every brick's default display text is its own pattern with spaces escaped. A TextNode already
            // carries them that way (EscapeSpaces is idempotent, so this is a no-op there); what this reaches
            // is the pattern-derived bricks a RegexPatternAttribute produced - enum member synonyms like
            // "each player's", terminal patterns like "((in|from) )?" - which must keep raw spaces in their
            // own Regex, since that text doubles as the identity EnumCaptureTraceSummary's synonym table is
            // keyed by (matched document text, not pattern text). Escaping display-side only keeps the
            // rendered regex uniform without touching that lookup, or the compiled pattern.
            brick.RegexFormatted = BuiltRegex.EscapeSpaces(brick.Regex);
        }

        var sequence = FoldAdheringJoiners(RemoveRawSynthesizedSectionBricks(bricks));
        List<RegexBrick> result = [];

        for (int i = 0; i < sequence.Count; i++)
        {
            var brick = sequence[i];

            if (includeSupplementalLines && ShouldInsertBlankLineBefore(sequence, i))
                result.Add(new RegexBrickBlank(_regexGraph.RootNode));

            BrickCommentResolver.Apply(brick);
            result.Add(brick);

            if (brick is RegexBrickGroupOpen groupOpen)
                ExpandGroupOpen(groupOpen, bricks, result, includeSupplementalLines);
        }

        return result;
    }

    /// <summary>
    /// Drops enum member value bricks and the pipe joiners between them (regenerated by <see cref="EnumSectionBuilder"/>
    /// as occurrence-ranked, synonym-grouped rows), and drops a dynamic group's raw literal-match pattern and
    /// inter-pattern joiners (regenerated by <see cref="DynamicSectionBuilder"/> as occurrence-ranked capture rows,
    /// or reinstated verbatim when there's no captured data) once their parent group is reached.
    /// Both joiner predicates rely on a joiner brick being attributed to the group it sits <em>inside</em>
    /// rather than the one it merely precedes (see the <c>owner</c> parameter on
    /// <c>RegexNode.AppendJoinerBrickIfWarranted</c>) - otherwise the ordinary sibling joiner in front of an
    /// enum/dynamic group reads as that group's own synthesized content and gets dropped here.
    /// </summary>
    static List<RegexBrick> RemoveRawSynthesizedSectionBricks(List<RegexBrick> bricks) =>
        bricks
            .Where(x => x is not RegexBrickValue)
            .Where(x => x is not RegexBrickJoiner joiner || joiner.NamedGroupParent is not EnumNode)
            .Where(x => x.NamedGroupParent is not DynamicGlyphNode || (x.Parent is not TextNode && x is not RegexBrickJoiner))
            .ToList();

    /// <summary>
    /// Folds a joiner that follows tight punctuation into the preceding brick's own line rather than letting
    /// it stand as a line of its own - so a <c>","</c> nib reads as <c>,[ ]</c>, the way the space is
    /// actually written when the nib is authored as <c>", "</c>. Purely positional: the joiner is still one
    /// brick's worth of pattern text in exactly the same place, it just shares a row. This is the mirror of
    /// <see cref="TextNode.StartsWithTightPunctuation"/> suppressing the joiner on the other side, and it
    /// reuses the same one-brick/two-span layout an enum member row already uses for its own leading joiner.
    /// Assigns <see cref="RegexBrick.RegexFormatted"/> absolutely (never appends to it), since bricks are
    /// shared per type and re-formatted on every render.
    /// </summary>
    static List<RegexBrick> FoldAdheringJoiners(List<RegexBrick> sequence)
    {
        List<RegexBrick> result = [];

        foreach (var brick in sequence)
        {
            if (brick is RegexBrickJoiner
                && result.LastOrDefault() is RegexBrick preceding
                && preceding.Parent is TextNode { EndsWithTightPunctuation: true })
            {
                preceding.RegexFormatted = BuiltRegex.EscapeSpaces(preceding.Regex) + brick.Regex;
                continue;
            }

            result.Add(brick);
        }

        return result;
    }

    /// <summary>
    /// A blank separator line goes before a brick unless it's the very first line, immediately follows a
    /// group open (nothing to separate from yet), or is one of two consecutive group closes (keeps nested
    /// closing brackets visually attached).
    /// </summary>
    static bool ShouldInsertBlankLineBefore(List<RegexBrick> sequence, int index) =>
        index > 0
        && sequence[index - 1] is not RegexBrickGroupOpen
        && !(sequence[index] is RegexBrickGroupClose && sequence[index - 1] is RegexBrickGroupClose);

    /// <summary>Simplifies a group-open brick's displayed name and, for enum/dynamic groups, appends its member/capture section.</summary>
    void ExpandGroupOpen(RegexBrickGroupOpen groupOpen, List<RegexBrick> allBricks, List<RegexBrick> result, bool includeSupplementalLines)
    {
        groupOpen.SetFormattedGroupName(_regexGraph.SimpleUniqueNames[groupOpen.FullyQualifiedName]);

        if (groupOpen.NamedGroupParent is EnumNode enumNode)
        {
            var enumSummary = _summary.EnumCaptureSummaries[enumNode.FullyQualifiedName];
            result.AddRange(_enumSectionBuilder.Build(enumNode, allBricks, enumSummary, _displayMode, includeOmittedCount: includeSupplementalLines));
            return;
        }

        if (groupOpen.NamedGroupParent is DynamicGlyphNode dynamicNode)
        {
            var dynamicSummary = _summary.DynamicCaptureSummaries[dynamicNode.FullyQualifiedName];
            result.AddRange(_dynamicSectionBuilder.Build(dynamicNode, allBricks, dynamicSummary, includeSupplementalLines, _displayMode));
        }
    }
}
