namespace Glyphotype.RegexGeneration.Presentation;

/// <summary>
/// Turns the raw, unfiltered brick sequence produced by walking a <see cref="RegexNode"/> graph into the
/// sequence that gets rendered as commented output. In order: enum member value bricks are dropped and
/// regenerated by <see cref="EnumSectionBuilder"/> as occurrence-ranked, synonym-grouped rows; group
/// names are simplified via <see cref="RegexGraph.SimpleUniqueNames"/>; every brick's display comment is
/// resolved via <see cref="BrickCommentResolver"/>; and blank-line bricks are inserted between logical
/// sections. This replaces what used to be a single large method (<c>SmartRegex.GetSpacedFilteredRegexBricks</c>).
/// </summary>
internal class RegexBrickFormattingPipeline
{
    readonly RegexGraph _regexGraph;
    readonly GlyphOccurrenceSummary _summary;
    readonly EnumSectionBuilder _enumSectionBuilder = new();
    readonly DynamicSectionBuilder _dynamicSectionBuilder = new();

    public RegexBrickFormattingPipeline(RegexGraph regexGraph, GlyphOccurrenceSummary summary)
    {
        _regexGraph = regexGraph;
        _summary = summary;
    }

    /// <summary>Runs the full formatting pass over <paramref name="bricks"/> and returns the final, render-ready brick sequence.</summary>
    /// <param name="includeSupplementalLines">
    /// Whether to include the purely-decorative/summary lines: <see cref="RegexBrickBlank"/> separators
    /// between logical sections, and each enum group's trailing <see cref="RegexBrickOmittedCount"/> row.
    /// </param>
    public List<RegexBrick> Format(List<RegexBrick> bricks, bool includeSupplementalLines = true)
    {
        // Bricks are shared/cached per type and re-formatted on every render. A brick embedded elsewhere
        // by DynamicSectionBuilder leaves depth/identity overrides applied on these same shared objects,
        // so a plain, non-embedded pass must clear them back to baseline here — otherwise a type rendered
        // on its own page would inherit stale depth or a rebased data-path from the last time it was
        // embedded inside some other type's dynamic capture. This must run over every raw brick, not just
        // the ones that survive RemoveRawSynthesizedSectionBricks below: enum member (RegexBrickValue)
        // bricks are filtered out of that sequence but re-fetched from this same unfiltered list by
        // EnumSectionBuilder, so they'd otherwise never get reset at all.
        foreach (var brick in bricks)
            brick.ResetEmbeddingOverrides();

        var sequence = RemoveRawSynthesizedSectionBricks(bricks);
        List<RegexBrick> result = [];

        for (int i = 0; i < sequence.Count; i++)
        {
            var brick = sequence[i];

            if (includeSupplementalLines && ShouldInsertBlankLineBefore(sequence, i))
                result.Add(new RegexBrickBlank(_regexGraph.RootNode));

            BrickCommentResolver.Apply(brick);
            result.Add(brick);

            if (brick is RegexBrickGroupOpen groupOpen)
                ExpandGroupOpen(groupOpen, bricks, result, includeSupplementalLines);
        }

        return result;
    }

    /// <summary>
    /// Drops enum member value bricks and the pipe joiners between them (regenerated by <see cref="EnumSectionBuilder"/>
    /// as occurrence-ranked, synonym-grouped rows), and drops a dynamic group's raw literal-match pattern and
    /// inter-pattern joiners (regenerated by <see cref="DynamicSectionBuilder"/> as occurrence-ranked capture rows,
    /// or reinstated verbatim when there's no captured data) once their parent group is reached.
    /// </summary>
    static List<RegexBrick> RemoveRawSynthesizedSectionBricks(List<RegexBrick> bricks) =>
        bricks
            .Where(x => x is not RegexBrickValue)
            .Where(x => x is not RegexBrickJoiner joiner || joiner.NamedGroupParent is not EnumNode)
            .Where(x => x.NamedGroupParent is not DynamicGlyphNode || (x.Parent is not TextNode && x is not RegexBrickJoiner))
            .ToList();

    /// <summary>
    /// A blank separator line goes before a brick unless it's the very first line, immediately follows a
    /// group open (nothing to separate from yet), or is one of two consecutive group closes (keeps nested
    /// closing brackets visually attached).
    /// </summary>
    static bool ShouldInsertBlankLineBefore(List<RegexBrick> sequence, int index) =>
        index > 0
        && sequence[index - 1] is not RegexBrickGroupOpen
        && !(sequence[index] is RegexBrickGroupClose && sequence[index - 1] is RegexBrickGroupClose);

    /// <summary>Simplifies a group-open brick's displayed name and, for enum/dynamic groups, appends its member/capture section.</summary>
    void ExpandGroupOpen(RegexBrickGroupOpen groupOpen, List<RegexBrick> allBricks, List<RegexBrick> result, bool includeSupplementalLines)
    {
        groupOpen.SetFormattedGroupName(_regexGraph.SimpleUniqueNames[groupOpen.FullyQualifiedName]);

        if (groupOpen.NamedGroupParent is EnumNode enumNode)
        {
            var enumSummary = _summary.EnumCaptureSummaries[enumNode.FullyQualifiedName];
            result.AddRange(_enumSectionBuilder.Build(enumNode, allBricks, enumSummary, includeOmittedCount: includeSupplementalLines));
            return;
        }

        if (groupOpen.NamedGroupParent is DynamicGlyphNode dynamicNode)
        {
            var dynamicSummary = _summary.DynamicCaptureSummaries[dynamicNode.FullyQualifiedName];
            result.AddRange(_dynamicSectionBuilder.Build(dynamicNode, allBricks, dynamicSummary, includeSupplementalLines));
        }
    }
}
