namespace MTGPlexer.RegexGeneration.Presentation;

/// <summary>
/// Turns the raw, unfiltered brick sequence produced by walking a <see cref="RegexNode"/> graph into the
/// sequence that gets rendered as commented output. In order: enum member value bricks are dropped and
/// regenerated by <see cref="EnumSectionBuilder"/> as occurrence-ranked, synonym-grouped rows; group
/// names are simplified via <see cref="RegexGraph.SimpleUniqueNames"/>; every brick's display comment is
/// resolved via <see cref="BrickCommentResolver"/>; and blank-line bricks are inserted between logical
/// sections. This replaces what used to be a single large method (<c>SmartRegex.GetSpacedFilteredRegexBricks</c>).
/// </summary>
internal class RegexBrickFormattingPipeline
{
    readonly RegexGraph _regexGraph;
    readonly TokenOccurrenceSummary _summary;
    readonly EnumSectionBuilder _enumSectionBuilder = new();

    public RegexBrickFormattingPipeline(RegexGraph regexGraph, TokenOccurrenceSummary summary)
    {
        _regexGraph = regexGraph;
        _summary = summary;
    }

    /// <summary>Runs the full formatting pass over <paramref name="bricks"/> and returns the final, render-ready brick sequence.</summary>
    public List<RegexBrick> Format(List<RegexBrick> bricks)
    {
        var sequence = RemoveRawEnumMemberBricks(bricks);
        List<RegexBrick> result = [];

        for (int i = 0; i < sequence.Count; i++)
        {
            var brick = sequence[i];

            if (ShouldInsertBlankLineBefore(sequence, i))
                result.Add(new RegexBrickBlank(_regexGraph.RootNode));

            BrickCommentResolver.Apply(brick);
            result.Add(brick);

            if (brick is RegexBrickGroupOpen groupOpen)
                ExpandGroupOpen(groupOpen, bricks, result);
        }

        return result;
    }

    /// <summary>
    /// Drops enum member value bricks and the pipe joiners between them; <see cref="EnumSectionBuilder"/>
    /// regenerates both as occurrence-ranked, synonym-grouped rows once their parent group is reached.
    /// </summary>
    static List<RegexBrick> RemoveRawEnumMemberBricks(List<RegexBrick> bricks) =>
        bricks
            .Where(x => x is not RegexBrickValue)
            .Where(x => x is not RegexBrickJoiner joiner || joiner.NamedGroupParent is not EnumNode)
            .ToList();

    /// <summary>
    /// A blank separator line goes before a brick unless it's the very first line, immediately follows a
    /// group open (nothing to separate from yet), or is one of two consecutive group closes (keeps nested
    /// closing brackets visually attached).
    /// </summary>
    static bool ShouldInsertBlankLineBefore(List<RegexBrick> sequence, int index) =>
        index > 0
        && sequence[index - 1] is not RegexBrickGroupOpen
        && !(sequence[index] is RegexBrickGroupClose && sequence[index - 1] is RegexBrickGroupClose);

    /// <summary>Simplifies a group-open brick's displayed name and, for enum groups, appends its member section.</summary>
    void ExpandGroupOpen(RegexBrickGroupOpen groupOpen, List<RegexBrick> allBricks, List<RegexBrick> result)
    {
        groupOpen.SetFormattedGroupName(_regexGraph.SimpleUniqueNames[groupOpen.FullyQualifiedName]);

        if (groupOpen.NamedGroupParent is not EnumNode enumNode)
            return;

        var enumSummary = _summary.EnumCaptureSummaries[enumNode.FullyQualifiedName];
        result.AddRange(_enumSectionBuilder.Build(enumNode, allBricks, enumSummary));
    }
}
